// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class EliminarContactTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void eliminarContact() {
    // Test name: Eliminar Contact
    // Step # | name | target | value | comment
    // 1 | open | http://192.168.196.39/Hotel/login.php |  | 
    driver.Navigate().GoToUrl("http://192.168.196.39/Hotel/login.php");
    // 2 | setWindowSize | 1552x840 |  | 
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    // 3 | click | linkText=Admin |  | 
    driver.FindElement(By.LinkText("Admin")).Click();
    // 4 | type | id=inputEmail | admin | 
    driver.FindElement(By.Id("inputEmail")).SendKeys("admin");
    // 5 | type | id=inputPassword | 1234 | 
    driver.FindElement(By.Id("inputPassword")).SendKeys("1234");
    // 6 | click | name=submit |  | 
    driver.FindElement(By.Name("submit")).Click();
    // 7 | click | linkText=Requests |  | 
    driver.FindElement(By.LinkText("Requests")).Click();
    // 8 | click | css=tr:nth-child(7) .fa |  | 
    driver.FindElement(By.CssSelector("tr:nth-child(7) .fa")).Click();
    // 9 | click | linkText=Log Out |  | 
    driver.FindElement(By.LinkText("Log Out")).Click();
  }
}
