// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class GaleriaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void galeria() {
    // Test name: Galeria
    // Step # | name | target | value | comment
    // 1 | open | http://192.168.196.39/Hotel/index.php |  | 
    driver.Navigate().GoToUrl("http://192.168.196.39/Hotel/index.php");
    // 2 | setWindowSize | 1552x840 |  | 
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    // 3 | click | linkText=Gallery |  | 
    driver.FindElement(By.LinkText("Gallery")).Click();
    // 4 | click | css=.col-sm-4:nth-child(1) .img-responsive |  | 
    driver.FindElement(By.CssSelector(".col-sm-4:nth-child(1) .img-responsive")).Click();
    // 5 | runScript | window.scrollTo(0,35.20000076293945) |  | 
    js.ExecuteScript("window.scrollTo(0,35.20000076293945)");
    // 6 | click | linkText=› |  | 
    driver.FindElement(By.LinkText("›")).Click();
    // 7 | click | linkText=› |  | 
    driver.FindElement(By.LinkText("›")).Click();
    // 8 | click | linkText=› |  | 
    driver.FindElement(By.LinkText("›")).Click();
    // 9 | click | linkText=› |  | 
    driver.FindElement(By.LinkText("›")).Click();
    // 10 | click | linkText=› |  | 
    driver.FindElement(By.LinkText("›")).Click();
    // 11 | click | linkText=› |  | 
    driver.FindElement(By.LinkText("›")).Click();
    // 12 | click | linkText=› |  | 
    driver.FindElement(By.LinkText("›")).Click();
    // 13 | click | linkText=› |  | 
    driver.FindElement(By.LinkText("›")).Click();
    // 14 | click | linkText=› |  | 
    driver.FindElement(By.LinkText("›")).Click();
    // 15 | click | linkText=› |  | 
    driver.FindElement(By.LinkText("›")).Click();
    // 16 | click | linkText=› |  | 
    driver.FindElement(By.LinkText("›")).Click();
    // 17 | click | linkText=× |  | 
    driver.FindElement(By.LinkText("×")).Click();
  }
}
