// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoginUsuarioInvalidoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void loginUsuarioInvalido() {
    // Test name: Login - Usuario Invalido
    // Step # | name | target | value | comment
    // 1 | open | http://192.168.196.39/Hotel/index.php |  | 
    driver.Navigate().GoToUrl("http://192.168.196.39/Hotel/index.php");
    // 2 | setWindowSize | 1552x840 |  | 
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    // 3 | click | linkText=Admin |  | 
    driver.FindElement(By.LinkText("Admin")).Click();
    // 4 | type | id=inputEmail | Prueba | 
    driver.FindElement(By.Id("inputEmail")).SendKeys("Prueba");
    // 5 | click | css=.row |  | 
    driver.FindElement(By.CssSelector(".row")).Click();
    // 6 | click | id=inputPassword |  | 
    driver.FindElement(By.Id("inputPassword")).Click();
    // 7 | type | id=inputPassword | 1234 | 
    driver.FindElement(By.Id("inputPassword")).SendKeys("1234");
    // 8 | click | name=submit |  | 
    driver.FindElement(By.Name("submit")).Click();
    // 9 | click | css=.row |  | 
    driver.FindElement(By.CssSelector(".row")).Click();
  }
}
