// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TarifasyHabitacionesTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tarifasyHabitaciones() {
    // Test name: Tarifas y Habitaciones
    // Step # | name | target | value | comment
    // 1 | open | http://192.168.196.39/Hotel/index.php |  | 
    driver.Navigate().GoToUrl("http://192.168.196.39/Hotel/index.php");
    // 2 | setWindowSize | 1552x840 |  | 
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    // 3 | click | linkText=Rooms & Tariff |  | 
    driver.FindElement(By.LinkText("Rooms & Tariff")).Click();
    // 4 | click | linkText=Check Details |  | 
    driver.FindElement(By.LinkText("Check Details")).Click();
    // 5 | click | linkText=Rooms & Tariff |  | 
    driver.FindElement(By.LinkText("Rooms & Tariff")).Click();
    // 6 | click | css=.col-sm-6:nth-child(2) .btn |  | 
    driver.FindElement(By.CssSelector(".col-sm-6:nth-child(2) .btn")).Click();
    // 7 | click | linkText=Rooms & Tariff |  | 
    driver.FindElement(By.LinkText("Rooms & Tariff")).Click();
    // 8 | click | css=.col-sm-6:nth-child(3) .btn |  | 
    driver.FindElement(By.CssSelector(".col-sm-6:nth-child(3) .btn")).Click();
    // 9 | click | linkText=Rooms & Tariff |  | 
    driver.FindElement(By.LinkText("Rooms & Tariff")).Click();
    // 10 | click | css=.col-sm-6:nth-child(4) .btn |  | 
    driver.FindElement(By.CssSelector(".col-sm-6:nth-child(4) .btn")).Click();
    // 11 | click | linkText=Rooms & Tariff |  | 
    driver.FindElement(By.LinkText("Rooms & Tariff")).Click();
    // 12 | click | css=.col-sm-6:nth-child(5) .btn |  | 
    driver.FindElement(By.CssSelector(".col-sm-6:nth-child(5) .btn")).Click();
    // 13 | click | linkText=Rooms & Tariff |  | 
    driver.FindElement(By.LinkText("Rooms & Tariff")).Click();
    // 14 | click | css=.col-sm-6:nth-child(6) .btn |  | 
    driver.FindElement(By.CssSelector(".col-sm-6:nth-child(6) .btn")).Click();
    // 15 | click | linkText=Rooms & Tariff |  | 
    driver.FindElement(By.LinkText("Rooms & Tariff")).Click();
  }
}
